### PR TITLE
issue#226 fix

### PR DESCRIPTION
**Pull request by kewlkiev**
This fix is for SNS alarms not being configured for each step and hence only final step's error messages are displayed in SNS alarms
https://github.com/coursera/dataduct/issues/226
@idralyuk @everanurag

### CODE REVIEW

**Comment by idralyuk** [comment]
@kewlkiev, thank you.

Can you add a [feature toggle](http://martinfowler.com/articles/feature-toggles.html) for this?

Some users might not want to see the full cascade of failures.

**Comment by kewlkiev** [comment]
@idralyuk have added feature toggle for cascade failures.
if YAML or config have
topic_arn configured and it starts with "all:" it will be enabled for all steps else only teardown step will consist of failure SNS configured.

so topic_arn will look like 
topic_arn: '**all:**arn:aws:sns:us-west-2:XXXXXXXXXX:YYYYYYYYYY' for all steps having SNS configured and 
topic_arn: 'arn:aws:sns:us-west-2:XXXXXXXXXX:YYYYYYYYYY'
for SNS only in teardown step

**Comment by kewlkiev** [comment]
also @idralyuk @everanurag  have added status in the subject itself, because otherwise lambda filtering was ignoring any onSuccess messages which were using same SNS object.
so that we can filter CASCADE_FAILED from the messages and at same time be able to not filter out success message because they don't have error trace.

**Comment by idralyuk** [comment]
Awesome, thank you, @kewlkiev

**Pull request merged**
